package io.github.somaruntime.soma.processor;

import java.io.IOException;
import java.io.OutputStream;
import java.io.OutputStreamWriter;
import java.io.Writer;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.annotation.processing.Filer;
import javax.lang.model.element.Element;
import javax.tools.FileObject;
import javax.tools.JavaFileObject;
import javax.tools.StandardLocation;

final class CompositionGenerator {

    private final Filer filer;

    CompositionGenerator(Filer filer) {
        this.filer = filer;
    }

    List<RenderedComposition> renderAll(List<CompositionModel> models) {
        List<RenderedComposition> rendered =
                new ArrayList<RenderedComposition>(models.size());
        for (CompositionModel model : models) {
            rendered.add(new RenderedComposition(
                    model,
                    renderSource(model),
                    renderManifest(model)));
        }
        return Collections.unmodifiableList(rendered);
    }

    void generateAll(List<RenderedComposition> compositions) throws IOException {
        for (RenderedComposition composition : compositions) {
            CompositionModel model = composition.model;
            Element[] origins = origins(model);
            JavaFileObject sourceFile = filer.createSourceFile(
                    model.generatedTypeName(), origins);
            try (Writer writer = sourceFile.openWriter()) {
                writer.write(composition.source);
            }
        }

        for (RenderedComposition composition : compositions) {
            CompositionModel model = composition.model;
            Element[] origins = origins(model);
            FileObject manifest = filer.createResource(
                    StandardLocation.CLASS_OUTPUT,
                    "",
                    model.manifestPath(),
                    origins);
            try (OutputStream output = manifest.openOutputStream();
                 Writer writer = new OutputStreamWriter(output, StandardCharsets.UTF_8)) {
                writer.write(composition.manifest);
            }
        }
    }

    private static Element[] origins(CompositionModel model) {
        return model.originatingElements().toArray(
                new Element[model.originatingElements().size()]);
    }

    private static String renderSource(CompositionModel model) {
        StringBuilder source = new StringBuilder(1024);
        source.append("// Generated by SOMA. Do not edit.\n")
                .append("package ").append(model.generatedPackage()).append(";\n\n")
                .append("final class SomaCompositionLinkage {\n")
                .append("    private static final String SCHEMA_PACKAGE = \"")
                .append(model.schemaPackage()).append("\";\n")
                .append("    private static final String PROCESSOR_VERSION = \"")
                .append(model.processorVersion()).append("\";\n")
                .append("    private static final String CONTRACT_VERSION = \"")
                .append(model.contractVersion()).append("\";\n")
                .append("    private static final String RUNTIME_BUILD_IDENTITY = \"")
                .append(model.runtimeBuildIdentity()).append("\";\n")
                .append("    private static final String FINGERPRINT = \"")
                .append(model.fingerprint()).append("\";\n\n")
                .append("    static {\n")
                .append("        io.github.somaruntime.soma.internal.SomaRuntimeLinkage")
                .append(".requireCompatible(PROCESSOR_VERSION, CONTRACT_VERSION, ")
                .append("RUNTIME_BUILD_IDENTITY);\n")
                .append("    }\n\n")
                .append("    private SomaCompositionLinkage() {\n")
                .append("    }\n\n")
                .append("    static String schemaPackage() {\n")
                .append("        return SCHEMA_PACKAGE;\n")
                .append("    }\n\n")
                .append("    static String fingerprint() {\n")
                .append("        return FINGERPRINT;\n")
                .append("    }\n")
                .append("}\n");
        return source.toString();
    }

    private static String renderManifest(CompositionModel model) {
        StringBuilder manifest = new StringBuilder(1024);
        appendProperty(manifest, "format", "1");
        appendProperty(manifest, "schema.package", model.schemaPackage());
        appendProperty(manifest, "generated.package", model.generatedPackage());
        appendProperty(manifest, "processor.version", model.processorVersion());
        appendProperty(manifest, "contract.version", model.contractVersion());
        appendProperty(manifest, "runtime.build.sha256", model.runtimeBuildIdentity());
        appendProperty(manifest, "fingerprint.sha256", model.fingerprint());
        appendProperty(manifest, "generated.files", model.generatedTypeName());
        appendProperty(manifest, "schema.line.count",
                Integer.toString(model.schemaLines().size()));
        List<String> lines = model.schemaLines();
        for (int index = 0; index < lines.size(); index++) {
            appendProperty(manifest, "schema.line." + index, lines.get(index));
        }
        return manifest.toString();
    }

    private static void appendProperty(
            StringBuilder target,
            String key,
            String value) {
        target.append(key).append('=');
        for (int index = 0; index < value.length(); index++) {
            char character = value.charAt(index);
            switch (character) {
                case '\\':
                    target.append("\\\\");
                    break;
                case '\t':
                    target.append("\\t");
                    break;
                case '\n':
                    target.append("\\n");
                    break;
                case '\r':
                    target.append("\\r");
                    break;
                case '\f':
                    target.append("\\f");
                    break;
                default:
                    if (character < 0x20 || character > 0x7e) {
                        target.append("\\u");
                        String hex = Integer.toHexString(character);
                        for (int padding = hex.length(); padding < 4; padding++) {
                            target.append('0');
                        }
                        target.append(hex);
                    } else {
                        target.append(character);
                    }
                    break;
            }
        }
        target.append('\n');
    }

    static final class RenderedComposition {

        private final CompositionModel model;
        private final String source;
        private final String manifest;

        private RenderedComposition(
                CompositionModel model,
                String source,
                String manifest) {
            this.model = model;
            this.source = source;
            this.manifest = manifest;
        }
    }
}
