package io.github.somaruntime.soma.processor;

import java.io.IOException;
import java.io.OutputStream;
import java.io.OutputStreamWriter;
import java.io.Writer;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.annotation.processing.Filer;
import javax.lang.model.element.Element;
import javax.tools.FileObject;
import javax.tools.JavaFileObject;
import javax.tools.StandardLocation;

final class CompositionGenerator {

    private final Filer filer;

    CompositionGenerator(Filer filer) {
        this.filer = filer;
    }

    List<RenderedComposition> renderAll(List<CompositionModel> models) {
        List<RenderedComposition> rendered =
                new ArrayList<RenderedComposition>(models.size());
        for (CompositionModel model : models) {
            List<RenderedSource> sources = renderSources(model);
            rendered.add(new RenderedComposition(
                    model,
                    sources,
                    renderManifest(model, sources)));
        }
        return Collections.unmodifiableList(rendered);
    }

    void generateAll(List<RenderedComposition> compositions) throws IOException {
        for (RenderedComposition composition : compositions) {
            Element[] origins = origins(composition.model);
            for (RenderedSource rendered : composition.sources) {
                JavaFileObject sourceFile = filer.createSourceFile(
                        rendered.typeName, origins);
                try (Writer writer = sourceFile.openWriter()) {
                    writer.write(rendered.source);
                }
            }
        }

        for (RenderedComposition composition : compositions) {
            CompositionModel model = composition.model;
            FileObject manifest = filer.createResource(
                    StandardLocation.CLASS_OUTPUT,
                    "",
                    model.manifestPath(),
                    origins(model));
            try (OutputStream output = manifest.openOutputStream();
                 Writer writer = new OutputStreamWriter(output, StandardCharsets.UTF_8)) {
                writer.write(composition.manifest);
            }
        }
    }

    private static Element[] origins(CompositionModel model) {
        return model.originatingElements().toArray(
                new Element[model.originatingElements().size()]);
    }

    private static List<RenderedSource> renderSources(CompositionModel model) {
        List<RenderedSource> result = new ArrayList<RenderedSource>();
        result.add(new RenderedSource(
                model.generatedTypeName(), renderLinkage(model)));
        if (model.supportsI1Surface()) {
            result.add(new RenderedSource(
                    model.generatedPackage() + ".Soma", renderSoma(model)));
            result.add(new RenderedSource(
                    model.generatedPackage() + ".SomaGroup", renderSomaGroup(model)));
            for (CompositionModel.TableModel table : model.tables()) {
                result.add(new RenderedSource(
                        model.generatedPackage() + "." + table.simpleName(),
                        renderDetachedObject(model, table)));
                result.add(new RenderedSource(
                        model.generatedPackage() + "."
                                + GeneratedNames.tableType(table.simpleName()),
                        renderTable(model, table)));
            }
        }
        return Collections.unmodifiableList(result);
    }

    private static String renderLinkage(CompositionModel model) {
        StringBuilder source = new StringBuilder(1400);
        source.append("// Generated by SOMA. Do not edit.\n")
                .append("package ").append(model.generatedPackage()).append(";\n\n")
                .append("final class SomaCompositionLinkage {\n")
                .append("    private static final java.lang.String SCHEMA_PACKAGE = \"")
                .append(model.schemaPackage()).append("\";\n")
                .append("    private static final java.lang.String PROCESSOR_VERSION = \"")
                .append(model.processorVersion()).append("\";\n")
                .append("    private static final java.lang.String CONTRACT_VERSION = \"")
                .append(model.contractVersion()).append("\";\n")
                .append("    private static final java.lang.String RUNTIME_BUILD_IDENTITY = \"")
                .append(model.runtimeBuildIdentity()).append("\";\n")
                .append("    private static final java.lang.String FINGERPRINT = \"")
                .append(model.fingerprint()).append("\";\n\n")
                .append("    static {\n")
                .append("        io.github.somaruntime.soma.internal.SomaRuntimeLinkage")
                .append(".requireCompatible(PROCESSOR_VERSION, CONTRACT_VERSION, ")
                .append("RUNTIME_BUILD_IDENTITY);\n")
                .append("    }\n\n")
                .append("    private SomaCompositionLinkage() {\n")
                .append("    }\n\n")
                .append("    static void requireLinked() {\n")
                .append("    }\n\n")
                .append("    static java.lang.String schemaPackage() {\n")
                .append("        return SCHEMA_PACKAGE;\n")
                .append("    }\n\n")
                .append("    static java.lang.String fingerprint() {\n")
                .append("        return FINGERPRINT;\n")
                .append("    }\n")
                .append("}\n");
        return source.toString();
    }

    private static String renderSoma(CompositionModel model) {
        StringBuilder source = header(model, 3000);
        source.append("public final class Soma {\n\n")
                .append("    private static final java.lang.Object CAPABILITY = ")
                .append("new java.lang.Object();\n\n")
                .append("    static {\n")
                .append("        SomaCompositionLinkage.requireLinked();\n")
                .append("    }\n\n")
                .append("    private Soma() {\n")
                .append("    }\n\n")
                .append("    public static void configure(\n")
                .append("            io.github.somaruntime.soma.SomaConfiguration configuration) {\n")
                .append("        io.github.somaruntime.soma.internal.GeneratedRuntime.configure(\n")
                .append("                java.lang.invoke.MethodHandles.lookup(), ")
                .append("CAPABILITY, configuration);\n")
                .append("    }\n\n")
                .append("    public static SomaGroup defaultGroup() {\n")
                .append("        io.github.somaruntime.soma.internal.GeneratedRuntime")
                .append(".freezeConfiguration(\n")
                .append("                java.lang.invoke.MethodHandles.lookup(), CAPABILITY);\n")
                .append("        return DefaultGroupHolder.INSTANCE;\n")
                .append("    }\n\n")
                .append("    public static SomaGroup createGroup() {\n")
                .append("        io.github.somaruntime.soma.internal.GeneratedRuntime")
                .append(".freezeConfiguration(\n")
                .append("                java.lang.invoke.MethodHandles.lookup(), CAPABILITY);\n")
                .append("        return newGroup();\n")
                .append("    }\n\n");
        for (CompositionModel.TableModel table : model.tables()) {
            String tableType = GeneratedNames.tableType(table.simpleName());
            String accessor = GeneratedNames.tableAccessor(table.simpleName());
            source.append("    public static ").append(tableType).append(' ')
                    .append(accessor).append("() {\n")
                    .append("        return defaultGroup().").append(accessor).append("();\n")
                    .append("    }\n\n");
        }
        source.append("    static boolean accepts(java.lang.Object candidate) {\n")
                .append("        return candidate == CAPABILITY;\n")
                .append("    }\n\n")
                .append("    private static SomaGroup newGroup() {\n")
                .append("        io.github.somaruntime.soma.internal.GeneratedGroup runtime = ")
                .append("io.github.somaruntime.soma.internal.GeneratedRuntime.createGroup(\n")
                .append("                java.lang.invoke.MethodHandles.lookup(), CAPABILITY);\n")
                .append("        return SomaGroup.create(CAPABILITY, runtime);\n")
                .append("    }\n\n")
                .append("    private static final class DefaultGroupHolder {\n")
                .append("        private static final SomaGroup INSTANCE = newGroup();\n")
                .append("    }\n")
                .append("}\n");
        return source.toString();
    }

    private static String renderSomaGroup(CompositionModel model) {
        StringBuilder source = header(model, 3500);
        source.append("public final class SomaGroup {\n\n")
                .append("    private final java.lang.Object capability;\n")
                .append("    private final io.github.somaruntime.soma.internal.GeneratedGroup ")
                .append("runtime;\n");
        for (CompositionModel.TableModel table : model.tables()) {
            source.append("    private volatile ")
                    .append(GeneratedNames.tableType(table.simpleName())).append(' ')
                    .append(GeneratedNames.tableAccessor(table.simpleName()))
                    .append(";\n");
        }
        source.append("\n    private SomaGroup(\n")
                .append("            java.lang.Object capability,\n")
                .append("            io.github.somaruntime.soma.internal.GeneratedGroup runtime) {\n")
                .append("        if (runtime == null) {\n")
                .append("            throw new java.lang.AssertionError(")
                .append("\"generated runtime Group is missing\");\n")
                .append("        }\n")
                .append("        runtime.requireCapability(capability);\n")
                .append("        this.capability = capability;\n")
                .append("        this.runtime = runtime;\n")
                .append("    }\n\n")
                .append("    static SomaGroup create(\n")
                .append("            java.lang.Object capability,\n")
                .append("            io.github.somaruntime.soma.internal.GeneratedGroup runtime) {\n")
                .append("        return new SomaGroup(capability, runtime);\n")
                .append("    }\n\n");
        for (CompositionModel.TableModel table : model.tables()) {
            String tableType = GeneratedNames.tableType(table.simpleName());
            String accessor = GeneratedNames.tableAccessor(table.simpleName());
            source.append("    public ").append(tableType).append(' ')
                    .append(accessor).append("() {\n")
                    .append("        ").append(tableType).append(" value = ")
                    .append(accessor).append(";\n")
                    .append("        if (value != null) {\n")
                    .append("            return value;\n")
                    .append("        }\n")
                    .append("        synchronized (this) {\n")
                    .append("            value = ").append(accessor).append(";\n")
                    .append("            if (value == null) {\n")
                    .append("                value = ").append(tableType)
                    .append(".create(capability, runtime);\n")
                    .append("                ").append(accessor).append(" = value;\n")
                    .append("            }\n")
                    .append("            return value;\n")
                    .append("        }\n")
                    .append("    }\n\n");
        }
        source.append("}\n");
        return source.toString();
    }

    private static String renderDetachedObject(
            CompositionModel model,
            CompositionModel.TableModel table) {
        StringBuilder source = header(model, 2400);
        source.append("public final class ").append(table.simpleName()).append(" {\n\n");
        for (CompositionModel.FieldModel field : table.fields()) {
            source.append("    private long ").append(field.name()).append(";\n");
        }
        source.append("\n    public ").append(table.simpleName()).append("() {\n")
                .append("    }\n\n")
                .append("    public ").append(table.simpleName()).append('(');
        appendParameters(source, table.fields());
        source.append(") {\n");
        for (CompositionModel.FieldModel field : table.fields()) {
            source.append("        this.").append(field.name()).append(" = ")
                    .append(field.name()).append(";\n");
        }
        source.append("    }\n\n");
        for (CompositionModel.FieldModel field : table.fields()) {
            source.append("    public long ").append(field.name()).append("() {\n")
                    .append("        return ").append(field.name()).append(";\n")
                    .append("    }\n\n")
                    .append("    public void ").append(field.name())
                    .append("(long value) {\n")
                    .append("        this.").append(field.name()).append(" = value;\n")
                    .append("    }\n\n");
        }
        source.append("}\n");
        return source.toString();
    }

    private static String renderTable(
            CompositionModel model,
            CompositionModel.TableModel table) {
        String tableType = GeneratedNames.tableType(table.simpleName());
        String objectType = model.generatedPackage() + "." + table.simpleName();
        int keyIndex = table.keyFieldIndex();
        CompositionModel.FieldModel key = table.fields().get(keyIndex);
        StringBuilder source = header(model, 12000);
        source.append("public final class ").append(tableType).append(" {\n\n")
                .append("    private final io.github.somaruntime.soma.internal")
                .append(".GeneratedLongTable runtime;\n\n");
        for (CompositionModel.FieldModel field : table.fields()) {
            source.append("    public final ").append(fieldType(field)).append(' ')
                    .append(field.name()).append(";\n");
        }
        source.append("\n    private ").append(tableType)
                .append("(java.lang.Object capability,\n")
                .append("            io.github.somaruntime.soma.internal.GeneratedGroup group) {\n")
                .append("        if (group == null) {\n")
                .append("            throw new java.lang.AssertionError(")
                .append("\"generated Group is missing\");\n")
                .append("        }\n")
                .append("        this.runtime = group.createLongTable(\n")
                .append("                java.lang.invoke.MethodHandles.lookup(), capability, \"")
                .append(table.simpleName()).append("\", ")
                .append(table.defaultCapacity()).append("L, ")
                .append(table.fields().size()).append(", ")
                .append(keyIndex).append(");\n");
        for (CompositionModel.FieldModel field : table.fields()) {
            source.append("        this.").append(field.name()).append(" = new ")
                    .append(fieldType(field)).append("();\n");
        }
        source.append("    }\n\n")
                .append("    static ").append(tableType)
                .append(" create(java.lang.Object capability,\n")
                .append("            io.github.somaruntime.soma.internal.GeneratedGroup group) {\n")
                .append("        return new ").append(tableType)
                .append("(capability, group);\n")
                .append("    }\n\n")
                .append("    public long size() {\n")
                .append("        return runtime.size();\n")
                .append("    }\n\n")
                .append("    public long capacity() {\n")
                .append("        return runtime.capacity();\n")
                .append("    }\n\n")
                .append("    public void reserve(long expectedRows) {\n")
                .append("        runtime.reserve(expectedRows);\n")
                .append("    }\n\n")
                .append("    public void add(").append(objectType).append(" value) {\n")
                .append("        runtime.requireArgument(value, ")
                .append("io.github.somaruntime.soma.SomaOperation.ADD, \"value\");\n")
                .append("        runtime.add(new long[] {");
        appendObjectReads(source, table.fields(), "value");
        source.append("});\n")
                .append("    }\n\n")
                .append("    public java.util.Optional<").append(objectType).append("> find(long ")
                .append(key.name()).append(") {\n")
                .append("        long[] values = runtime.find(").append(key.name()).append(");\n")
                .append("        return values == null ? java.util.Optional.empty() ")
                .append(": java.util.Optional.of(materialize(values));\n")
                .append("    }\n\n")
                .append("    public ").append(objectType).append(" get(long ")
                .append(key.name()).append(") {\n")
                .append("        return materialize(runtime.get(").append(key.name()).append("));\n")
                .append("    }\n\n")
                .append("    public io.github.somaruntime.soma.UpdateResult update(\n")
                .append("            long ").append(key.name()).append(",\n")
                .append("            final java.util.function.Consumer<? super Editor> updater) {\n")
                .append("        runtime.requireArgument(updater, ")
                .append("io.github.somaruntime.soma.SomaOperation.UPDATE, \"updater\");\n")
                .append("        return runtime.update(").append(key.name()).append(", updater,\n")
                .append("                new io.github.somaruntime.soma.internal")
                .append(".LongEditorCallback() {\n")
                .append("                    @java.lang.Override\n")
                .append("                    public void accept(\n")
                .append("                            io.github.somaruntime.soma.internal")
                .append(".LongEditorSession session) {\n")
                .append("                        updater.accept(Editor.create(session));\n")
                .append("                    }\n")
                .append("                });\n")
                .append("    }\n\n")
                .append("    public long count() {\n")
                .append("        return runtime.count();\n")
                .append("    }\n\n")
                .append("    public Selection selectAll() {\n")
                .append("        return Selection.create(runtime.selectAll());\n")
                .append("    }\n\n")
                .append("    public Selection filter(")
                .append("io.github.somaruntime.soma.SomaExpression<View> expression) {\n")
                .append("        return Selection.create(runtime.filter(expression));\n")
                .append("    }\n\n")
                .append("    private static ").append(objectType)
                .append(" materialize(long[] values) {\n")
                .append("        return new ").append(objectType).append('(');
        appendArrayReads(source, table.fields().size(), "values");
        source.append(");\n")
                .append("    }\n\n");

        appendViewAndEditor(source, model, table);
        appendSelection(source);
        for (int index = 0; index < table.fields().size(); index++) {
            appendFieldEndpoint(source, table.fields().get(index), index);
        }
        source.append("}\n");
        return source.toString();
    }

    private static void appendViewAndEditor(
            StringBuilder source,
            CompositionModel model,
            CompositionModel.TableModel table) {
        String objectType = model.generatedPackage() + "." + table.simpleName();
        source.append("    public static class View {\n\n")
                .append("        private final io.github.somaruntime.soma.internal")
                .append(".LongEditorSession session;\n\n")
                .append("        private View(io.github.somaruntime.soma.internal")
                .append(".LongEditorSession session) {\n")
                .append("            this.session = session;\n")
                .append("        }\n\n");
        for (int index = 0; index < table.fields().size(); index++) {
            CompositionModel.FieldModel field = table.fields().get(index);
            source.append("        public long ").append(field.name()).append("() {\n")
                    .append("            return session.value(").append(index).append(");\n")
                    .append("        }\n\n");
        }
        source.append("        public ").append(objectType).append(" fetch() {\n")
                .append("            return new ").append(objectType).append('(');
        appendMethodReads(source, table.fields(), "this");
        source.append(");\n")
                .append("        }\n")
                .append("    }\n\n")
                .append("    public static final class Editor extends View {\n\n")
                .append("        private final io.github.somaruntime.soma.internal")
                .append(".LongEditorSession session;\n\n")
                .append("        private Editor(io.github.somaruntime.soma.internal")
                .append(".LongEditorSession session) {\n")
                .append("            super(session);\n")
                .append("            this.session = session;\n")
                .append("        }\n\n")
                .append("        private static Editor create(")
                .append("io.github.somaruntime.soma.internal.LongEditorSession session) {\n")
                .append("            return new Editor(session);\n")
                .append("        }\n\n");
        for (int index = 0; index < table.fields().size(); index++) {
            CompositionModel.FieldModel field = table.fields().get(index);
            if (field.role() != CompositionModel.FieldRole.KEY) {
                source.append("        public void ").append(field.name())
                        .append("(long value) {\n")
                        .append("            session.value(").append(index).append(", value);\n")
                        .append("        }\n\n");
            }
        }
        source.append("        @java.lang.Override\n")
                .append("        public ").append(objectType).append(" fetch() {\n")
                .append("            return super.fetch();\n")
                .append("        }\n")
                .append("    }\n\n");
    }

    private static void appendSelection(StringBuilder source) {
        source.append("    public static final class Selection {\n\n")
                .append("        private final io.github.somaruntime.soma.internal")
                .append(".GeneratedLongPipeline pipeline;\n\n")
                .append("        private Selection(io.github.somaruntime.soma.internal")
                .append(".GeneratedLongPipeline pipeline) {\n")
                .append("            this.pipeline = pipeline;\n")
                .append("        }\n\n")
                .append("        private static Selection create(")
                .append("io.github.somaruntime.soma.internal.GeneratedLongPipeline pipeline) {\n")
                .append("            return new Selection(pipeline);\n")
                .append("        }\n\n")
                .append("        public Selection filter(")
                .append("io.github.somaruntime.soma.SomaExpression<View> expression) {\n")
                .append("            return new Selection(pipeline.filter(expression));\n")
                .append("        }\n\n")
                .append("        public long count() {\n")
                .append("            return pipeline.count();\n")
                .append("        }\n")
                .append("    }\n\n");
    }

    private static void appendFieldEndpoint(
            StringBuilder source,
            CompositionModel.FieldModel field,
            int fieldIndex) {
        source.append("    public final class ").append(fieldType(field))
                .append(" implements io.github.somaruntime.soma.SomaKeyableField<")
                .append("View, java.lang.Long> {\n\n")
                .append("        private ").append(fieldType(field)).append("() {\n")
                .append("        }\n\n");
        appendComparison(source, "eq", fieldIndex);
        appendComparison(source, "ne", fieldIndex);
        appendComparison(source, "lt", fieldIndex);
        appendComparison(source, "le", fieldIndex);
        appendComparison(source, "gt", fieldIndex);
        appendComparison(source, "ge", fieldIndex);
        source.append("        public io.github.somaruntime.soma.SomaExpression<View> between(\n")
                .append("                long lowerInclusive,\n")
                .append("                long upperInclusive) {\n")
                .append("            return runtime.between(").append(fieldIndex)
                .append(", lowerInclusive, upperInclusive);\n")
                .append("        }\n\n")
                .append("        public io.github.somaruntime.soma.SomaExpression<View> ")
                .append("in(long... values) {\n")
                .append("            return runtime.in(").append(fieldIndex).append(", values);\n")
                .append("        }\n")
                .append("    }\n\n");
    }

    private static void appendComparison(
            StringBuilder source,
            String name,
            int fieldIndex) {
        source.append("        public io.github.somaruntime.soma.SomaExpression<View> ")
                .append(name)
                .append("(long value) {\n")
                .append("            return runtime.").append(name).append('(')
                .append(fieldIndex).append(", value);\n")
                .append("        }\n\n");
    }

    private static StringBuilder header(CompositionModel model, int capacity) {
        return new StringBuilder(capacity)
                .append("// Generated by SOMA. Do not edit.\n")
                .append("package ").append(model.generatedPackage()).append(";\n\n");
    }

    private static void appendParameters(
            StringBuilder source,
            List<CompositionModel.FieldModel> fields) {
        for (int index = 0; index < fields.size(); index++) {
            if (index != 0) {
                source.append(", ");
            }
            source.append("long ").append(fields.get(index).name());
        }
    }

    private static void appendObjectReads(
            StringBuilder source,
            List<CompositionModel.FieldModel> fields,
            String receiver) {
        for (int index = 0; index < fields.size(); index++) {
            if (index != 0) {
                source.append(", ");
            }
            source.append(receiver).append('.').append(fields.get(index).name()).append("()");
        }
    }

    private static void appendMethodReads(
            StringBuilder source,
            List<CompositionModel.FieldModel> fields,
            String receiver) {
        appendObjectReads(source, fields, receiver);
    }

    private static void appendArrayReads(
            StringBuilder source,
            int fieldCount,
            String receiver) {
        for (int index = 0; index < fieldCount; index++) {
            if (index != 0) {
                source.append(", ");
            }
            source.append(receiver).append('[').append(index).append(']');
        }
    }

    private static String fieldType(CompositionModel.FieldModel field) {
        return GeneratedNames.fieldEndpointType(field.name());
    }

    private static String renderManifest(
            CompositionModel model,
            List<RenderedSource> sources) {
        StringBuilder manifest = new StringBuilder(1400);
        appendProperty(manifest, "format", "1");
        appendProperty(manifest, "schema.package", model.schemaPackage());
        appendProperty(manifest, "generated.package", model.generatedPackage());
        appendProperty(manifest, "processor.version", model.processorVersion());
        appendProperty(manifest, "contract.version", model.contractVersion());
        appendProperty(manifest, "runtime.build.sha256", model.runtimeBuildIdentity());
        appendProperty(manifest, "fingerprint.sha256", model.fingerprint());
        StringBuilder generatedFiles = new StringBuilder();
        for (RenderedSource source : sources) {
            if (generatedFiles.length() != 0) {
                generatedFiles.append(',');
            }
            generatedFiles.append(source.typeName);
        }
        appendProperty(manifest, "generated.files", generatedFiles.toString());
        appendProperty(manifest, "schema.line.count",
                Integer.toString(model.schemaLines().size()));
        List<String> lines = model.schemaLines();
        for (int index = 0; index < lines.size(); index++) {
            appendProperty(manifest, "schema.line." + index, lines.get(index));
        }
        return manifest.toString();
    }

    private static void appendProperty(
            StringBuilder target,
            String key,
            String value) {
        target.append(key).append('=');
        for (int index = 0; index < value.length(); index++) {
            char character = value.charAt(index);
            switch (character) {
                case '\\':
                    target.append("\\\\");
                    break;
                case '\t':
                    target.append("\\t");
                    break;
                case '\n':
                    target.append("\\n");
                    break;
                case '\r':
                    target.append("\\r");
                    break;
                case '\f':
                    target.append("\\f");
                    break;
                default:
                    if (character < 0x20 || character > 0x7e) {
                        target.append("\\u");
                        String hex = Integer.toHexString(character);
                        for (int padding = hex.length(); padding < 4; padding++) {
                            target.append('0');
                        }
                        target.append(hex);
                    } else {
                        target.append(character);
                    }
                    break;
            }
        }
        target.append('\n');
    }

    static final class RenderedComposition {

        private final CompositionModel model;
        private final List<RenderedSource> sources;
        private final String manifest;

        private RenderedComposition(
                CompositionModel model,
                List<RenderedSource> sources,
                String manifest) {
            this.model = model;
            this.sources = sources;
            this.manifest = manifest;
        }
    }

    private static final class RenderedSource {

        private final String typeName;
        private final String source;

        private RenderedSource(String typeName, String source) {
            this.typeName = typeName;
            this.source = source;
        }
    }
}
