package io.github.somaruntime.soma;

/** Stable machine-readable failure categories. */
public enum SomaFailureCode {
    INVALID_ARGUMENT,
    DUPLICATE_KEY,
    MISSING_KEY,
    MISSING_RELATION_SIDE,
    NULL_VALUE_UNSUPPORTED,
    RESOURCE_LIMIT_EXCEEDED,
    ARITHMETIC_OVERFLOW,
    CONCURRENT_GROUP_OPERATION,
    REENTRANT_GROUP_OPERATION,
    NESTED_PARALLEL_OPERATION,
    CONFIGURATION_FROZEN,
    PARALLEL_EXECUTOR_UNAVAILABLE,
    OPERATION_CANCELLED,
    PIPELINE_ALREADY_CONSUMED,
    CALLBACK_SCOPE_VIOLATION,
    CALLBACK_FAILED
}
