package com.hgtech.soma.processor;

import static com.hgtech.soma.processor.DenseSourceNames.q;
import static com.hgtech.soma.processor.DenseTableCodegenModel.TableSpec;

/** Emits packed Candidate Scan execution fragments into the Table artifact. */
final class DenseScanExecutionSourceSupport {
    private DenseScanExecutionSourceSupport() {
    }

    static void appendPackedTableTerminalExecutors(SourceBuilder out, TableSpec table) {
        String tableType = table.name("Table");
        String carrierType = table.carrierType;
        String scanType = table.name("Scan");
        out.append("  private static boolean packedAnyMatch(").append(tableType).append(" table,").append(scanType).append(".Predicate value){return packedMatch(table,value,true);}\n")
                .append("  private static boolean packedNoneMatch(").append(tableType).append(" table,").append(scanType).append(".Predicate value){return !packedMatch(table,value,false);}\n")
                .append("  private static boolean packedMatch(").append(tableType).append(" table,").append(scanType).append(".Predicate value,boolean any){if(value==null)throw new NullPointerException(\"predicate\");String op=any?\"scan.anyMatch\":\"scan.noneMatch\",callback=any?\"scan.anyMatch.predicate\":\"scan.noneMatch.predicate\";table.begin(op);long scanned=0L,reached=0L;try{").append(scanType).append(".Cursor c=new ").append(scanType).append(".Cursor(table);int size=table.size();for(int base=0;base<size;){int end=table.storageSegmentEndExclusive(base,size);for(int row=base;row<end;row++){scanned++;reached++;c.open(row);table.beginCallback(callback);boolean matched;try{matched=value.test(c);}catch(SomaRuntimeException failure){throw failure;}catch(RuntimeException failure){throw RuntimeFailures.callbackFailed(")
                .append(q(table.logicalName)).append(",op,\"predicate\",failure);}finally{table.endCallback(callback);c.close();}if(matched){table.endSuccess(op,scanned,reached,0L);return true;}}base=end;}table.endSuccess(op,scanned,reached,0L);return false;}catch(SomaRuntimeException failure){table.endFailure(op,scanned,reached,failure);throw failure;}catch(RuntimeException failure){table.abort(op);throw failure;}catch(Error failure){table.abort(op);throw failure;}}\n")
                .append("  private static void packedForEach(").append(tableType).append(" table,").append(scanType).append(".Consumer value){if(value==null)throw new NullPointerException(\"consumer\");table.begin(\"scan.forEach\");long scanned=0L;try{").append(scanType).append(".Cursor c=new ").append(scanType).append(".Cursor(table);int size=table.size();for(int base=0;base<size;){int end=table.storageSegmentEndExclusive(base,size);for(int row=base;row<end;row++){scanned++;c.open(row);table.beginCallback(\"scan.forEach.consumer\");try{value.accept(c);}catch(SomaRuntimeException failure){throw failure;}catch(RuntimeException failure){throw RuntimeFailures.callbackFailed(")
                .append(q(table.logicalName)).append(",\"scan.forEach\",\"consumer\",failure);}finally{table.endCallback(\"scan.forEach.consumer\");c.close();}}base=end;}table.endSuccess(\"scan.forEach\",scanned,scanned,0L);}catch(SomaRuntimeException failure){table.endFailure(\"scan.forEach\",scanned,scanned,failure);throw failure;}catch(RuntimeException failure){table.abort(\"scan.forEach\");throw failure;}catch(Error failure){table.abort(\"scan.forEach\");throw failure;}}\n")
                .append("  private static Optional<").append(carrierType).append("> packedFindFirst(").append(tableType).append(" table,MaterializationBudget budget){if(budget==null)throw new NullPointerException(\"budget\");table.begin(\"scan.findFirst\");long reached=0L;try{int row=table.size()==0?-1:0;reached=row<0?0L:1L;Optional<").append(carrierType).append("> result=table.materializeOptionalRow(row,budget,\"scan.findFirst\",true);table.endSuccess(\"scan.findFirst\",reached,reached,0L);return result;}catch(SomaRuntimeException failure){table.endFailure(\"scan.findFirst\",reached,reached,failure);throw failure;}catch(RuntimeException failure){table.abort(\"scan.findFirst\");throw failure;}catch(Error failure){table.abort(\"scan.findFirst\");throw failure;}}\n")
                .append("  private static ").append(carrierType).append(" packedFirstOrThrow(").append(tableType).append(" table,MaterializationBudget budget){if(budget==null)throw new NullPointerException(\"budget\");table.begin(\"scan.firstOrThrow\");long reached=0L;try{int row=table.size()==0?-1:0;reached=row<0?0L:1L;").append(carrierType).append(" result=table.materializeRequiredRow(row,budget,\"scan.firstOrThrow\",true,")
                .append(q(table.logicalName)).append(");table.endSuccess(\"scan.firstOrThrow\",1L,1L,0L);return result;}catch(SomaRuntimeException failure){table.endFailure(\"scan.firstOrThrow\",reached,reached,failure);throw failure;}catch(RuntimeException failure){table.abort(\"scan.firstOrThrow\");throw failure;}catch(Error failure){table.abort(\"scan.firstOrThrow\");throw failure;}}\n")
                .append("  private static List<").append(carrierType).append("> packedFetchAll(").append(tableType).append(" table,MaterializationBudget budget){if(budget==null)throw new NullPointerException(\"budget\");table.begin(\"scan.fetchAll\");long reached=0L;try{int count=table.size();int[] rows=table.preparePipelineScratch(count);for(int i=0;i<count;i++)rows[i]=i;reached=count;List<").append(carrierType).append("> result=table.materializeRows(rows,count,budget,\"scan.fetchAll\",true);table.endSuccess(\"scan.fetchAll\",reached,reached,0L);return result;}catch(SomaRuntimeException failure){table.endFailure(\"scan.fetchAll\",reached,reached,failure);throw failure;}catch(RuntimeException failure){table.abort(\"scan.fetchAll\");throw failure;}catch(Error failure){table.abort(\"scan.fetchAll\");throw failure;}}\n")
                .append("  private static IndexSnapshot packedIndexSnapshot(").append(tableType).append(" table){table.begin(\"scan.indexSnapshot\");long reached=0L;try{int count=table.size();int[] rows=table.preparePipelineScratch(count);for(int i=0;i<count;i++)rows[i]=i;reached=count;IndexSnapshot result=table.indexSnapshot(rows,count);table.endSuccess(\"scan.indexSnapshot\",reached,reached,0L);return result;}catch(SomaRuntimeException failure){table.endFailure(\"scan.indexSnapshot\",reached,reached,failure);throw failure;}catch(RuntimeException failure){table.abort(\"scan.indexSnapshot\");throw failure;}catch(Error failure){table.abort(\"scan.indexSnapshot\");throw failure;}}\n")
                .append("  private static UpdateResult packedUpdate(").append(tableType).append(" table,").append(scanType).append(".Updater value){if(value==null)throw new NullPointerException(\"updater\");table.preflightMutation(\"scan.update\");table.begin(\"scan.update\");long reached=0L,scanned=0L;boolean selected=false;int count=0;try{count=table.size();int[] rows=table.preparePipelineScratch(count);for(int i=0;i<count;i++)rows[i]=i;scanned=count;selected=true;table.prepareUpdateScratch(count);table.loadUpdateScratch(rows,count);").append(scanType).append(".MutableCursor c=new ").append(scanType).append(".MutableCursor(table);for(int i=0;i<count;i++){reached++;c.open(i,rows[i]);table.beginCallback(\"scan.update.updater\");try{value.update(c);}catch(SomaRuntimeException failure){throw failure;}catch(RuntimeException failure){throw RuntimeFailures.callbackFailed(")
                .append(q(table.logicalName)).append(",\"scan.update\",\"updater\",failure);}finally{table.endCallback(\"scan.update.updater\");c.close();}}long changed=table.publishUpdate(rows,count);table.endSuccess(\"scan.update\",scanned,count,changed);return table.updateResult(scanned,count,changed);}catch(SomaRuntimeException failure){table.endFailure(\"scan.update\",scanned,reached,failure);throw failure;}catch(RuntimeException failure){table.abort(\"scan.update\");throw failure;}catch(Error failure){table.abort(\"scan.update\");throw failure;}finally{if(selected)table.clearUpdateScratch(count);}}\n")
                .append("  private static RemoveResult packedRemove(").append(tableType).append(" table){table.preflightMutation(\"scan.remove\");table.begin(\"scan.remove\");long scanned=0L;try{int count=table.size();int[] rows=table.preparePipelineScratch(count);for(int i=0;i<count;i++)rows[i]=i;scanned=count;RemoveResult result=table.removeSelected(rows,count,scanned,\"scan.remove\");table.endSuccess(\"scan.remove\",scanned,count,count);return result;}catch(SomaRuntimeException failure){table.endFailure(\"scan.remove\",scanned,scanned,failure);throw failure;}catch(RuntimeException failure){table.abort(\"scan.remove\");throw failure;}catch(Error failure){table.abort(\"scan.remove\");throw failure;}}\n");
    }
}
